# Generated by Django 4.0.6 on 2022-07-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(null=True)),
                ('address_from', models.CharField(max_length=128, null=True)),
                ('address_to', models.CharField(max_length=128, null=True)),
                ('hash', models.CharField(max_length=256, null=True)),
                ('transaction_index', models.IntegerField(null=True)),
                ('data_input', models.TextField(default='0x', null=True)),
                ('nonce', models.IntegerField(blank=True, null=True)),
                ('gas_used', models.PositiveBigIntegerField(null=True)),
                ('gas_price', models.PositiveBigIntegerField(null=True)),
                ('value', models.PositiveBigIntegerField(default=0, null=True)),
                ('status', models.IntegerField(null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'BSC',
                'abstract': False,
            },
        ),
    ]
