# Generated by Django 4.0.6 on 2022-08-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuroraBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=68, null=True)),
                ('difficulty', models.CharField(max_length=68, null=True)),
                ('hash', models.CharField(max_length=68, null=True)),
                ('miner', models.CharField(max_length=42, null=True)),
                ('number', models.IntegerField(null=True, unique=True)),
                ('size', models.IntegerField(default=0, null=True)),
                ('transactions_count', models.IntegerField(null=True)),
                ('gas_used', models.CharField(default='0', max_length=68)),
            ],
            options={
                'db_table': 'AuroraBlock',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuroraPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, null=True)),
                ('factory_address', models.CharField(max_length=42)),
                ('pair_address', models.CharField(max_length=42, unique=True)),
                ('token0', models.CharField(max_length=42)),
                ('token1', models.CharField(max_length=42)),
                ('pair_symbol', models.CharField(max_length=12)),
                ('factory_symbol', models.CharField(blank=True, max_length=42, null=True)),
                ('token0_symbol', models.CharField(blank=True, max_length=12, null=True)),
                ('token1_symbol', models.CharField(blank=True, max_length=12, null=True)),
                ('token0_decimals', models.IntegerField(null=True)),
                ('token1_decimals', models.IntegerField(null=True)),
                ('decimals', models.IntegerField(default=18)),
                ('pair_updated', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'AuroraPair',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSCBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=68, null=True)),
                ('difficulty', models.CharField(max_length=68, null=True)),
                ('hash', models.CharField(max_length=68, null=True)),
                ('miner', models.CharField(max_length=42, null=True)),
                ('number', models.IntegerField(null=True, unique=True)),
                ('size', models.IntegerField(default=0, null=True)),
                ('transactions_count', models.IntegerField(null=True)),
                ('gas_used', models.CharField(default='0', max_length=68)),
            ],
            options={
                'db_table': 'BSCBlock',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BSCPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, null=True)),
                ('factory_address', models.CharField(max_length=42)),
                ('pair_address', models.CharField(max_length=42, unique=True)),
                ('token0', models.CharField(max_length=42)),
                ('token1', models.CharField(max_length=42)),
                ('pair_symbol', models.CharField(max_length=12)),
                ('factory_symbol', models.CharField(blank=True, max_length=42, null=True)),
                ('token0_symbol', models.CharField(blank=True, max_length=12, null=True)),
                ('token1_symbol', models.CharField(blank=True, max_length=12, null=True)),
                ('token0_decimals', models.IntegerField(null=True)),
                ('token1_decimals', models.IntegerField(null=True)),
                ('decimals', models.IntegerField(default=18)),
                ('pair_updated', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'BSCPair',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BscEthSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, null=True)),
                ('reserve0', models.CharField(default=0, max_length=256)),
                ('reserve1', models.CharField(default=0, max_length=256)),
                ('hash', models.CharField(max_length=66, null=True)),
                ('block_number', models.IntegerField(null=True)),
                ('transaction_index', models.IntegerField(null=True)),
                ('pair_address', models.CharField(max_length=42)),
                ('method', models.CharField(max_length=66)),
                ('block_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchains.bscblock')),
                ('pair_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchains.bscpair')),
            ],
            options={
                'db_table': 'BscEthSyncEvent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuroraEthSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, null=True)),
                ('reserve0', models.CharField(default=0, max_length=256)),
                ('reserve1', models.CharField(default=0, max_length=256)),
                ('hash', models.CharField(max_length=66, null=True)),
                ('block_number', models.IntegerField(null=True)),
                ('transaction_index', models.IntegerField(null=True)),
                ('pair_address', models.CharField(max_length=42)),
                ('method', models.CharField(max_length=66)),
                ('block_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchains.aurorablock')),
                ('pair_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchains.aurorapair')),
            ],
            options={
                'db_table': 'AuroraEthSyncEvent',
                'abstract': False,
            },
        ),
    ]
