# Generated by Django 4.0.6 on 2022-07-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BSC',
            new_name='BSCTransaction',
        ),
        migrations.AlterModelTable(
            name='bsctransaction',
            table='BSCTransaction',
        ),
    ]
