# Generated by Django 4.0.6 on 2022-08-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bscethsyncevent',
            name='bsc_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchains.bscpair'),
        ),
        migrations.AlterField(
            model_name='bscpairtransaction',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchains.bscpair'),
        ),
    ]
