# Generated by Django 4.0.6 on 2022-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bscpair',
            name='factory_symbol',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='bscpair',
            name='token0_symbol',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='bscpair',
            name='token1_symbol',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
