# Generated by Django 4.0.6 on 2022-08-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0002_alter_bscethsyncevent_bsc_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bscpair',
            name='decimals',
            field=models.IntegerField(default=18),
        ),
    ]
