# Generated by Django 4.0.6 on 2022-08-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0003_aurorablock_aurorapair_auroraethsyncevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auroraethsyncevent',
            old_name='bsc_block',
            new_name='block_model',
        ),
        migrations.RenameField(
            model_name='auroraethsyncevent',
            old_name='bsc_pair',
            new_name='pair_model',
        ),
    ]
