# Generated by Django 4.0.6 on 2022-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0005_rename_bsc_block_bscethsyncevent_block_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aurorapair',
            name='token0_decimals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aurorapair',
            name='token1_decimals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bscpair',
            name='token0_decimals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bscpair',
            name='token1_decimals',
            field=models.IntegerField(null=True),
        ),
    ]
