version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh -c "
                    python manage.py makemigrations &
                    python manage.py migrate &
                    python manage.py runserver &&
                    python manage.py add_pairs &
                    python manage.py update_new_pairs &
                    python manage.py update_db_loop
                   "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: 
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
  django-lite:
    build: .
    command: sh -c "
                    python manage.py makemigrations &
                    python manage.py migrate --database=sqllite &
                    python manage.py runserver &&
                    python manage.py add_pairs &
                    python manage.py update_new_pairs &
                    python manage.py update_db_loop
                   "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: 
      - .env

volumes:
  db-data:
  web:
  django-lite:
  